#!/bin/bash
modman clone https://github.com/fbrnc/Aoe_Scheduler.git
modman clone https://github.com/fbrnc/Aoe_JsCssTstamp.git
modman clone https://github.com/fbrnc/Aoe_LogViewer.git
modman clone https://github.com/fbrnc/Aoe_QuoteCleaner.git
modman clone https://github.com/fbrnc/Aoe_Profiler.git
modman clone https://github.com/fbrnc/Aoe_AsyncCache.git
modman clone https://github.com/fbrnc/Aoe_TemplateHints.git
modman clone https://github.com/fbrnc/Aoe_ClassPathCache.git
modman clone https://github.com/fbrnc/Aoe_ModelCache.git
modman clone https://github.com/fbrnc/Aoe_SuffixFix.git
modman clone https://github.com/fbrnc/Aoe_CreateSampleData.git
modman clone https://github.com/fbrnc/Aoe_ManageStores.git
modman clone https://github.com/fbrnc/Aoe_ReuseImages.git
modman clone https://github.com/fbrnc/Aoe_LayoutConditions.git
modman clone https://github.com/fbrnc/Aoe_FilePicker.git
modman clone https://github.com/fbrnc/Aoe_DesignFallback.git
modman clone https://github.com/fbrnc/Aoe_ApiLog.git
modman clone https://github.com/fbrnc/Aoe_Apc.git
modman clone https://github.com/fbrnc/Aoe_Static.git
modman clone https://github.com/fbrnc/Aoe_Opt.git
modman clone https://github.com/fbrnc/Aoe_DbSession.git
modman clone https://github.com/fbrnc/Aoe_CacheCleaner.git
modman clone https://github.com/fbrnc/Aoe_StaticDemo.git